### ISSUE TITLE
Random echo print_r in CaldavClient.php

### ISSUE THREAD

**Issue by MyIgel** [x3tech/caldav-client#1]
[CaldavClient.php:236](https://github.com/x3tech/caldav-client/blob/214dd0baa15e27d676c6d1cbbabd9adcc7355af1/src/CaldavClient.php#L236) and [CaldavClient.php:L244](https://github.com/x3tech/caldav-client/blob/214dd0baa15e27d676c6d1cbbabd9adcc7355af1/src/CaldavClient.php#L244)

**Comment by 3onyc** [comment]
I should have a linter warning about `print_r()` statements, thanks for reporting! Also apologies for the late fix, only just now noticed the ticket.
